//! DeBERTa-v3 tokenizer (DebertaV2-class SentencePiece Unigram).
//!
//! Loads the HuggingFace `tokenizer.json` directly via the
//! `tokenizers` crate, which mirrors the Python `tokenizers` package
//! used by `transformers.AutoTokenizer`. The pipeline is:
//!
//!   - **Normalizer**: `Strip` (whitespace) + `Precompiled`
//!     (SentencePiece charsmap from the Unigram model).
//!   - **PreTokenizer**: `Metaspace` (`▁` replacement,
//!     `add_prefix_space: true`).
//!   - **Model**: `Unigram` — the SPM vocabulary.
//!   - **PostProcessor**: `TemplateProcessing` that wraps a single
//!     input as `[CLS] A [SEP]` and a pair as `[CLS] A [SEP] B [SEP]`.
//!   - **Decoder**: `Metaspace` (reverses `▁` → space).
//!
//! Loading via `tokenizer.json` is byte-identical to HF's
//! `AutoTokenizer.from_pretrained(...).encode_plus(...)` provided
//! `truncation`, `padding`, and `add_special_tokens` are configured
//! to match. The Rust wrapper here exposes the canonical NLI shape
//! ([`Encoded::for_pair`]) so the diagnose pillar doesn't have to
//! think about the underlying mechanics.
//!
//! Verification: the test suite reads
//! `fixtures/tokenizer_pairs.json` (generated by
//! `scripts/hf_reference_tokenizer.py`) and asserts every (premise,
//! hypothesis) pair's encoded `(token_ids, attention_mask)` matches
//! the HF reference exactly. Re-run the script if you change any
//! pipeline component; the diff in the fixture is the contract.

use std::path::{Path, PathBuf};

use tokenizers::Tokenizer;

/// Errors building or using the tokenizer.
#[derive(Debug)]
pub enum TokenizerError {
    MissingFile(PathBuf),
    Load(String),
    Encode(String),
}

impl std::fmt::Display for TokenizerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingFile(p) => write!(f, "missing file: {}", p.display()),
            Self::Load(s) => write!(f, "load: {s}"),
            Self::Encode(s) => write!(f, "encode: {s}"),
        }
    }
}

impl std::error::Error for TokenizerError {}

/// DeBERTa-v3 tokenizer wrapper.
pub struct DebertaTokenizer {
    inner: Tokenizer,
    pub cls_id: u32,
    pub sep_id: u32,
    pub pad_id: u32,
    pub unk_id: u32,
}

/// One encoded input (or input pair) ready to feed into the model.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Encoded {
    pub token_ids: Vec<u32>,
    pub attention_mask: Vec<u32>,
    pub token_strings: Vec<String>,
}

impl DebertaTokenizer {
    /// Load from a HuggingFace-style model directory containing
    /// `tokenizer.json`.
    pub fn from_dir(dir: impl AsRef<Path>) -> Result<Self, TokenizerError> {
        let path = dir.as_ref().join("tokenizer.json");
        if !path.exists() {
            return Err(TokenizerError::MissingFile(path));
        }
        let inner = Tokenizer::from_file(&path)
            .map_err(|e| TokenizerError::Load(e.to_string()))?;

        // Look up the canonical special-token ids by string.
        let cls_id = inner
            .token_to_id("[CLS]")
            .ok_or_else(|| TokenizerError::Load("[CLS] missing from vocab".into()))?;
        let sep_id = inner
            .token_to_id("[SEP]")
            .ok_or_else(|| TokenizerError::Load("[SEP] missing from vocab".into()))?;
        let pad_id = inner
            .token_to_id("[PAD]")
            .ok_or_else(|| TokenizerError::Load("[PAD] missing from vocab".into()))?;
        let unk_id = inner
            .token_to_id("[UNK]")
            .ok_or_else(|| TokenizerError::Load("[UNK] missing from vocab".into()))?;

        Ok(Self { inner, cls_id, sep_id, pad_id, unk_id })
    }

    /// Encode a single text as `[CLS] tokens [SEP]`.
    pub fn encode_single(&self, text: &str) -> Result<Encoded, TokenizerError> {
        let enc = self
            .inner
            .encode(text, true)
            .map_err(|e| TokenizerError::Encode(e.to_string()))?;
        Ok(materialize(&enc))
    }

    /// Encode a (premise, hypothesis) pair as
    /// `[CLS] premise [SEP] hypothesis [SEP]`. This is the canonical
    /// NLI shape DeBERTa expects.
    pub fn encode_pair(
        &self,
        premise: &str,
        hypothesis: &str,
    ) -> Result<Encoded, TokenizerError> {
        let enc = self
            .inner
            .encode((premise.to_string(), hypothesis.to_string()), true)
            .map_err(|e| TokenizerError::Encode(e.to_string()))?;
        Ok(materialize(&enc))
    }

    /// Number of tokens in the underlying vocabulary (including
    /// special tokens).
    pub fn vocab_size(&self) -> usize {
        self.inner.get_vocab_size(true)
    }

    /// Decode token ids back to text. Used for round-trip tests and
    /// for surfacing tokenizer-level diagnostics.
    pub fn decode(&self, ids: &[u32]) -> Result<String, TokenizerError> {
        self.inner
            .decode(ids, true)
            .map_err(|e| TokenizerError::Encode(e.to_string()))
    }
}

impl std::fmt::Debug for DebertaTokenizer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DebertaTokenizer")
            .field("vocab_size", &self.vocab_size())
            .field("cls_id", &self.cls_id)
            .field("sep_id", &self.sep_id)
            .field("pad_id", &self.pad_id)
            .field("unk_id", &self.unk_id)
            .finish()
    }
}

fn materialize(enc: &tokenizers::Encoding) -> Encoded {
    Encoded {
        token_ids: enc.get_ids().to_vec(),
        attention_mask: enc.get_attention_mask().to_vec(),
        token_strings: enc.get_tokens().to_vec(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    use serde::Deserialize;

    #[derive(Debug, Deserialize)]
    struct Fixture {
        special_tokens: SpecialTokens,
        pairs: Vec<PairCase>,
    }

    #[derive(Debug, Deserialize)]
    struct SpecialTokens {
        cls_id: u32,
        sep_id: u32,
        pad_id: u32,
        unk_id: u32,
    }

    #[derive(Debug, Deserialize)]
    struct PairCase {
        name: String,
        premise: String,
        hypothesis: String,
        token_ids: Vec<u32>,
        attention_mask: Vec<u32>,
        token_strings: Vec<String>,
    }

    fn workspace_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .map(|p| p.to_path_buf())
            .expect("workspace root")
    }

    fn model_dir() -> Option<PathBuf> {
        let p = workspace_root().join("models/deberta-v3-large-mnli");
        if p.join("tokenizer.json").exists() {
            Some(p)
        } else {
            None
        }
    }

    fn load_fixture() -> Option<Fixture> {
        let p = workspace_root()
            .join("crates/jouleclaw-deberta/fixtures/tokenizer_pairs.json");
        if !p.exists() {
            return None;
        }
        let raw = std::fs::read_to_string(&p).ok()?;
        serde_json::from_str(&raw).ok()
    }

    #[test]
    fn special_token_ids_match_fixture() {
        let Some(dir) = model_dir() else {
            eprintln!("skip: model not downloaded");
            return;
        };
        let Some(fx) = load_fixture() else {
            eprintln!("skip: fixture missing — run scripts/hf_reference_tokenizer.py");
            return;
        };
        let tok = DebertaTokenizer::from_dir(&dir).expect("load tokenizer");
        assert_eq!(tok.cls_id, fx.special_tokens.cls_id, "CLS id mismatch");
        assert_eq!(tok.sep_id, fx.special_tokens.sep_id, "SEP id mismatch");
        assert_eq!(tok.pad_id, fx.special_tokens.pad_id, "PAD id mismatch");
        assert_eq!(tok.unk_id, fx.special_tokens.unk_id, "UNK id mismatch");
    }

    #[test]
    fn vocab_size_matches_model_config() {
        let Some(dir) = model_dir() else {
            eprintln!("skip: model not downloaded");
            return;
        };
        let tok = DebertaTokenizer::from_dir(&dir).expect("load");
        // The Unigram model carries 128000 SentencePiece pieces; HF
        // adds 5 special tokens via the added_tokens table, but the
        // tokenizers crate reports them inconsistently depending on
        // whether `with_added_tokens=true` is passed. The exact
        // count we observe with `get_vocab_size(true)` for this
        // model is 128001 (one of the special tokens already lives
        // in the base vocab so isn't re-added). Tolerate the small
        // spread; what matters is that the four canonical special
        // ids resolve.
        let v = tok.vocab_size();
        assert!(
            (128000..=128100).contains(&v),
            "vocab size {v} outside expected 128000-128100 range"
        );
    }

    #[test]
    fn pair_encoding_matches_hf_reference_token_for_token() {
        let Some(dir) = model_dir() else {
            eprintln!("skip: model not downloaded");
            return;
        };
        let Some(fx) = load_fixture() else {
            eprintln!("skip: fixture missing — run scripts/hf_reference_tokenizer.py");
            return;
        };
        let tok = DebertaTokenizer::from_dir(&dir).expect("load tokenizer");

        for case in &fx.pairs {
            let enc = tok
                .encode_pair(&case.premise, &case.hypothesis)
                .unwrap_or_else(|e| panic!("[{}] encode_pair failed: {e}", case.name));

            assert_eq!(
                enc.token_ids, case.token_ids,
                "[{}] token_ids diverged. premise={:?} hypothesis={:?}\n  got: {:?}\n  ref: {:?}",
                case.name, case.premise, case.hypothesis, enc.token_ids, case.token_ids
            );
            assert_eq!(
                enc.attention_mask, case.attention_mask,
                "[{}] attention_mask diverged", case.name
            );
            assert_eq!(
                enc.token_strings, case.token_strings,
                "[{}] token strings diverged", case.name
            );
        }
    }

    #[test]
    fn first_pair_uses_canonical_cls_sep_layout() {
        let Some(dir) = model_dir() else {
            eprintln!("skip: model not downloaded");
            return;
        };
        let tok = DebertaTokenizer::from_dir(&dir).expect("load");
        let enc = tok
            .encode_pair("Paris is the capital of France.", "France's capital is Paris.")
            .expect("encode_pair");
        assert_eq!(enc.token_ids.first().copied(), Some(tok.cls_id));
        assert_eq!(enc.token_ids.last().copied(), Some(tok.sep_id));
        let sep_count = enc.token_ids.iter().filter(|&&t| t == tok.sep_id).count();
        assert_eq!(sep_count, 2, "expected exactly 2 [SEP] in NLI pair encoding");
    }

    #[test]
    fn round_trip_decodes_premise_text() {
        let Some(dir) = model_dir() else {
            eprintln!("skip: model not downloaded");
            return;
        };
        let tok = DebertaTokenizer::from_dir(&dir).expect("load");
        let enc = tok.encode_single("Paris is the capital of France.").expect("enc");
        let back = tok.decode(&enc.token_ids).expect("decode");
        // The SPM decoder strips one leading space but otherwise
        // restores. Just check the content is there.
        assert!(back.contains("Paris"));
        assert!(back.contains("capital"));
        assert!(back.contains("France"));
    }

    #[test]
    fn missing_dir_returns_structured_error() {
        let err = DebertaTokenizer::from_dir("/tmp/nope-deberta").unwrap_err();
        assert!(matches!(err, TokenizerError::MissingFile(_)));
    }
}
